---
plugins:
  - stylelint-scss
  - stylelint-prettier
extends:
  - stylelint-config-standard
  - stylelint-config-tailwindcss
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
  - stylelint-prettier
ignoreFiles:
  - "**/*.min.css"
  - "**/node_modules/*"
rules:
  prettier/prettier: [true, { "singleQuote": false, "tabWidth": 2 }]

  # Allow Tailwind CSS directives
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - "tailwind"
        - "apply"
        - "variants"
        - "responsive"
        - "screen"
        - "layer"
  
  # Allow Tailwind utility classes and CSS variables
  selector-class-pattern: null
  
  max-nesting-depth: 2
  block-no-empty: true
  color-named: always-where-possible
  color-no-invalid-hex: true
  color-function-notation: modern
  no-duplicate-selectors: true
  font-family-name-quotes: always-where-required
  length-zero-no-unit: true
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - layer
        - variants
        - responsive
        - screen
